### PR TITLE
[Hacktoberfest contribution] Spanish translation Fix (Native-speaker rev) + Add a concept

### PR DESCRIPTION
**Pull request by Glis**
Hi there!!!

I wanted to contribute to this awesome repo that I think's priceless 🤩 

When I was going to add my new concepts, I saw that the Spanish file was a bit off (links didn't work, wrong translations, misplaced items, etc) 
**So I cleaned it**. 

There are still some definitions left to add from english to Spanish tho, but this is my humble bit 😊 
I also added a new definition to contribute to the knowledge base 😉 

I hope it's ok with you!
Happy Hacktoberfest!

### CODE REVIEW

**Comment by Glis** [comment]
Updated for resolving conflicts.
@dephraiim Could you check this changes?

There are many, so i'm staying tuned to any comment from your side 😊

**Comment by dephraiim** [comment]
it looks good. I used a bot to translate so I knew that there would be some errors. Thank You.

**Review by dephraiim — APPROVED** [review]
LGTM

**Comment by Glis** [comment]
TYSM for the approval. I hope this continues to grow cuz it's a nice resource.

**Pull request merged**
